DiscUtils/DiscUtils

- Library/DiscUtils.Core/Vfs/VfsFileSystem.cs
Check result of GetDirectoryEntry() for null before trying to reference
it.
> Fix NullReferenceException

- Tests/LibraryTests/Iso9660/Data/Readme.md
I did some more digging and I think I found the source of the bad iso-9660 image. I think it makes sense to document the issue here.
> Bad iso-9660 image

- Library/DiscUtils.Iso9660/BaseVolumeDescriptor.cs
- Library/DiscUtils.Iso9660/CDReader.cs
- Library/DiscUtils.Iso9660/VfsCDReader.cs
I broke iso-9660 file detection in one of my previous commits. This fixes it, while retaining the enforcement when opening a file.
> Fix iso-9660 detection

- Library/DiscUtils.Core/Setup/SetupHelper.cs
- Library/DiscUtils.Core/VolumeManager.cs
- Library/DiscUtils/DiscUtils.csproj
- Library/DiscUtils/SetupHelper.cs
- Tests/LibraryTests/Lvm/Data/lvm2.zip
- Tests/LibraryTests/Lvm/SampleDataTests.cs
Fixes the registration of the Lvm2 LogicalVolumeManagerFactory.
I've also added a sample file and a unit tests. The sample file contains three (mostly empty) logical volumes with overlapping data ranges.
> Include Lvm2 in DiscUtils.Complete

- Library/DiscUtils.Xfs/AllocationGroup.cs
- Library/DiscUtils.Xfs/AllocationGroupFreeBlockInfo.cs
- Library/DiscUtils.Xfs/AllocationGroupInodeBtreeInfo.cs
- Library/DiscUtils.Xfs/BTreeExtentLeaf.cs
- Library/DiscUtils.Xfs/BTreeExtentNode.cs
- Library/DiscUtils.Xfs/BTreeExtentRoot.cs
- Library/DiscUtils.Xfs/BTreeHeader.cs
- Library/DiscUtils.Xfs/BTreeInodeLeaf.cs
- Library/DiscUtils.Xfs/BTreeInodeLeave.cs
- Library/DiscUtils.Xfs/BTreeInodeNode.cs
- Library/DiscUtils.Xfs/Directory.cs
- Library/DiscUtils.Xfs/Extent.cs
- Library/DiscUtils.Xfs/SuperBlock.cs
- Library/DiscUtils.Xfs/VfsXfsFileSystem.cs
- Library/DiscUtils/DiscUtils.csproj
- Library/DiscUtils/SetupHelper.cs
- Tests/LibraryTests/Xfs/Data/xfs.zip
- Tests/LibraryTests/Xfs/SampleDataTests.cs
- multiblock directory extents (Extent.BlockCount > 1)
- calculation of AG offsets (mostly copied from kernel)
- support for Superblock Version 5 ([Self Describing Metadata](https://www.kernel.org/doc/Documentation/filesystems/xfs-self-describing-metadata.txt))
- unit test
> Xfs Bugfixes & Test

- Library/DiscUtils.Vhdx/DiskImageFile.cs
- Library/DiscUtils.Vhdx/LogEntry.cs
- Tests/LibraryTests/Vhdx/Data/vhdx-log-replay.zip
- Tests/LibraryTests/Vhdx/LogReplayTest.cs
Implementation is based on the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/mt740033.aspx).
I've also added a vhdx test file which is empty without a log replay, but contains a valid partition table inside the log.
> Vhdx log replay

- Library/DiscUtils.Streams/BuiltStream.cs
- Tests/LibraryTests/Streams/BuiltStreamTest.cs
Currently it is possible to read data after the end of a BuiltStream, if the size of all extents is larger than the length of the BuiltStream.
This can be reproduced by calling `Read()` with a count larger than number of remaining bytes.
I've also added an unit test, which validates the fix.
> respect length of BuiltStream

- Library/DiscUtils.Ntfs/Bitmap.cs
- Library/DiscUtils.Ntfs/NtfsFileSystem.cs
- Library/DiscUtils.Streams/Util/BitCounter.cs
I've found a major performance penalty in the space usage calculation of NTFS. Currenty the ClusterBitmap is read byte by byte from the underlying disk. This result in runtimes of up to one minute for large filesystems (>1TiB fs with a bitmap >50MiB).
I've changed the implementation to read the bitmap in blocks of 4K, which increased the performance by > 99% (in my test from ~1200ms down to ~45ms).
As a second optimization I've added a BitCounter which uses a precalculated lookup table to further speed up the size calculation from ~45ms down to ~15ms.
> Performance optimization for size info in NTFS

- Library/DiscUtils.Lvm/Metadata.cs
The BitDefender GravityZone Virtual Disk contains an LVM2 which has an invalid creation time. This PR adds a check against DateTime.MaxValue to prevent an exception for this case.
```
swap { ...
creation_time = 13815016539583152127
} 
root { ...
creation_time = 9268243417079996778
} ...
...
creation_host = "rescuecd"	# Linux rescuecd 4.4.5-gentoo-x86 #1 SMP Fri Mar 11 13:59:43 UTC 2016 i686
...
```
> fix LVM2 creation_time > DateTime.MaxValue

- Library/DiscUtils.Xfs/Properties/AssemblyInfo.cs
- Library/DiscUtils.Xfs/Symlink.cs
- Tests/LibraryTests/LibraryTests.csproj
- Tests/LibraryTests/Xfs/SampleDataTests.cs
- Tests/LibraryTests/Xfs/XfsTests.cs
Fixes the resolution of symlinks - previously the NULL terminator was ignored, resulting in the symlink not beeing resolved.
> XFS Symlink Target NULL Terminator

- Library/DiscUtils.Core/DiscFileLocator.cs
- Library/DiscUtils.Core/FileLocator.cs
- Library/DiscUtils.Core/Internal/LocalFileLocator.cs
- Library/DiscUtils.Core/NativeFileSystem.cs
- Library/DiscUtils.Core/Raw/Disk.cs
- Library/DiscUtils.Core/Setup/FileOpenEventArgs.cs
- Library/DiscUtils.Core/Setup/SetupHelper.cs
- Library/DiscUtils.Dmg/DiskFactory.cs
- Library/DiscUtils.Iso9660/BuildFileInfo.cs
- Library/DiscUtils.OpticalDisk/Disc.cs
- Library/DiscUtils.Registry/RegistryHive.cs
- Library/DiscUtils.SquashFs/BuilderFile.cs
- Library/DiscUtils.SquashFs/SquashFileSystemBuilder.cs
- Library/DiscUtils.Vdi/Disk.cs
- Library/DiscUtils.Vmdk/DiskImageFile.cs
- Utilities/DiscUtils.Diagnostics/TracingStream.cs
This adds the option to modify the parameters for any FileStream, which is opened inside DiscUtils.
The first commit adds the LocalFileLocator (I've skipped the standalone binaries from Utilities), to reduce the number of places, where files are opened. The second commit introduces an event, which can be used to modify the parameters (filename, mode, share & access), wrap the filestream or return a completly different stream.
This allows us to modify the FileShare parameter for vhdx files (as described in #24) or wrap all FileStreams to workaround a huge performance penalty  (factor > 1000) in the `FileStream.Length` Property for files residing on a Cluster Shared Volume (CSV).
This may also be useful for unit testing, because the files to be opened don't even have to exist.
> Allow interception of File.Open / new FileStream()

- Library/DiscUtils.Xfs/AllocationGroup.cs
- Library/DiscUtils.Xfs/AllocationGroupInodeBtreeInfo.cs
- Library/DiscUtils.Xfs/BTreeInodeNode.cs
- Library/DiscUtils.Xfs/Directory.cs
- Library/DiscUtils.Xfs/Inode.cs
Currently the calculation from agblock number to byte offset may be incorrect due to Uint32 overflows.
We had an example where the AGI root of the 5th allocation group was `2121031`. This is multiplied by `SuperBlock.Blocksize` to calculate the offset inside the AG. With a Blocksize of 4096 this results in an uint overflow (97808384 instead of 8687742976).
> fix offset calculation for xfs

- Library/DiscUtils.Core/LogicalVolumeInfo.cs
- Library/DiscUtils.Core/PhysicalVolumeInfo.cs
Makes the PhysicalVolumeInfo and PartitionInfo public, to check the partition type of a logical volume. We currently use this to filter [MSR](https://en.wikipedia.org/wiki/Microsoft_Reserved_Partition) partitions.
> Expose PhysicalVolumeInfo & PartitionInfo

- Library/DiscUtils.Ext/SuperBlock.cs
- Library/DiscUtils.Ext/VfsExtFileSystem.cs
Add support for opening ext filesystems with an unclean journal (as the summary states, it's save for reading and ext is always readonly).
Also fixes a wrong offset for some superblock fields (which looks like an old typo) and adds the missing incompat feature flag for ext4 64bit support.
> Ext bugfix & support for unclean journal

- Library/DiscUtils.Ntfs/Directory.cs
Huge improvement in performance when browsing a folder with lot of files.
The actual implementation was creating a `List<DirectoryIndexEntry>` with all the entries and each `RemoveAt` was causing an internal re-creation of the list with `Array.Copy`.
This caused a big slow down.
As a comparison with the actual implementation, the `DiscFileSystem.GetFiles(string path)` of a folder containing **500K** files it takes more than **20 minutes**.
With the proposed change it takes **3 seconds**.
> Improve NTFS performance when filtering entries

- Library/DiscUtils.Nfs/IRpcClient.cs
- Library/DiscUtils.Nfs/IRpcTransport.cs
- Library/DiscUtils.Nfs/MountProc3.cs
- Library/DiscUtils.Nfs/Nfs3.cs
- Library/DiscUtils.Nfs/Nfs3Client.cs
- Library/DiscUtils.Nfs/Nfs3Mount.cs
- Library/DiscUtils.Nfs/NfsProc3.cs
- Library/DiscUtils.Nfs/RpcClient.cs
- Library/DiscUtils.Nfs/RpcProgram.cs
- Library/DiscUtils.Nfs/RpcTcpTransport.cs
Extract an IRpcClient and IRpcTransport interfaces. This allows mocking the RPC client & RPC transport in unit tests.
> Extract IRpcClient and IRpcTransport interfaces

- Library/DiscUtils.Nfs/Nfs3.cs
- Library/DiscUtils.Nfs/Nfs3Export.cs
- Library/DiscUtils.Nfs/Nfs3FileSystemStat.cs
- Library/DiscUtils.Nfs/Nfs3FileSystemStatResult.cs
- Tests/LibraryTests/Nfs/Nfs3FileSystemStatResultTest.cs
- Tests/LibraryTests/Nfs/Nfs3FileSystemStatTest.cs
Add read/write support to the `FileSystemStat` and `FileSystemStatResult` classes. Should be the latest change to the NFS RPC objects.
> NFS: Make FileSystemStat, FileSystemStatResult read/write

- Library/DiscUtils.Nfs/IRpcObject.cs
- Library/DiscUtils.Nfs/Nfs3.cs
- Library/DiscUtils.Nfs/Nfs3CallResult.cs
- Library/DiscUtils.Nfs/Nfs3CreateResult.cs
- Library/DiscUtils.Nfs/Nfs3ExportResult.cs
- Library/DiscUtils.Nfs/Nfs3FileSystemInfoResult.cs
- Library/DiscUtils.Nfs/Nfs3FileSystemStatResult.cs
- Library/DiscUtils.Nfs/Nfs3GetAttributesResult.cs
- Library/DiscUtils.Nfs/Nfs3LookupResult.cs
- Library/DiscUtils.Nfs/Nfs3ModifyResult.cs
- Library/DiscUtils.Nfs/Nfs3MountResult.cs
- Library/DiscUtils.Nfs/Nfs3ReadDirPlusResult.cs
- Library/DiscUtils.Nfs/Nfs3ReadResult.cs
- Library/DiscUtils.Nfs/Nfs3WriteResult.cs
- Library/DiscUtils.Nfs/RpcAuthentication.cs
- Library/DiscUtils.Nfs/RpcCallHeader.cs
- Library/DiscUtils.Nfs/RpcMessageHeader.cs
- Library/DiscUtils.Nfs/RpcProgram.cs
- Library/DiscUtils.Nfs/XdrDataReader.cs
- Library/DiscUtils.Nfs/XdrDataWriter.cs
- Tests/LibraryTests/Nfs/RpcCallHeaderTest.cs
This PR exposes the NFS API so you can reuse it from a 3rd party library. Fits into the discussion whether we should include a NFS server in DiscUtils or not.
- Exposes the `XdrDataReader` and `XdrDataWriter` classes and makes the constructors of the RPC objects public.
- Adds a `IRpcObject` interface to any object which can be serialized to RPC. 
- Fixes the casing of some values of the `NfsProc3` enumeration
- Makes the `Proc` field of `RpcCallHeader` an `int` instead of a value of the `NfsProc3` enumeration. The RPC protocol is program-agnostic and defines Proc as an integer; individual RPC programs can later cast these values.
> Expose NFS3 API

- Library/DiscUtils.Nfs/Nfs3AccessResult.cs
- Library/DiscUtils.Nfs/Nfs3GetAttributesResult.cs
- Library/DiscUtils.Nfs/Nfs3PathConfResult.cs
- Library/DiscUtils.Nfs/Nfs3ReadDirResult.cs
- Tests/LibraryTests/Nfs/Nfs3AccessResultTest.cs
- Tests/LibraryTests/Nfs/Nfs3PathConfResultTest.cs
- Tests/LibraryTests/Nfs/Nfs3ReadDirResultTest.cs
Adds:
* [`Nfs3PathConfResult`](https://tools.ietf.org/html/rfc1813#page-90) (Procedure 20: PATHCONF - Retrieve POSIX information)
* [`Nfs3ReadDirResult`](https://tools.ietf.org/html/rfc1813#page-75) (Procedure 16: READDIR - Read From Directory)
Makes `Nfs3AccessResult` read/write.
> Add more NFS3 objects

- Library/DiscUtils.Nfs/PortMap2.cs
- Library/DiscUtils.Nfs/PortMap2Mapping.cs
- Library/DiscUtils.Nfs/PortMap2Port.cs
- Library/DiscUtils.Nfs/PortMap2Protocol.cs
- Library/DiscUtils.Nfs/PortMapProc2.cs
- Library/DiscUtils.Nfs/PortMapperProtocol.cs
- Library/DiscUtils.Nfs/RpcClient.cs
- Library/DiscUtils.Nfs/RpcProgram.cs
- Tests/LibraryTests/Nfs/PortMap2MappingTest.cs
- Tests/LibraryTests/Nfs/PortMap2PortTest.cs
The NFS client includes an implementation of the [RPC: Remote Procedure Call Protocol Version 2 (RFC5531)](https://tools.ietf.org/html/rfc5531) protocol and protocols that use the RPC protocol for communications:
- The [NFS Version 3 Protocol (RFC5531)](https://tools.ietf.org/html/rfc1813)
- The [Mount protocol (RFC5531, Appendix 1)](https://tools.ietf.org/html/rfc1813#page-106)
- The [Port Mapper protocol](http://pubs.opengroup.org/onlinepubs/9629799/chap6.htm)
For the NFS and Mount protocol, a specific naming convention was used:
- {Protocol}Proc{Version} is an enum which specifies the different procedures
- {Protocol}{Version}{Object} for the RPC objects
- {Protocol}{Version} for the clients
This PR updates the PortMapper client to use the same naming conventions, and makes some of the …
> Update PortMapper implementation to be consistent with NFS, Mount protocol

- Library/DiscUtils.Nfs/Nfs3AccessPermissions.cs
- Library/DiscUtils.Nfs/Nfs3CommitResult.cs
- Library/DiscUtils.Nfs/Nfs3CreateMode.cs
- Library/DiscUtils.Nfs/Nfs3DirectoryEntry.cs
- Library/DiscUtils.Nfs/Nfs3FileHandle.cs
* Add missing Nfs3CommitResult, Nfs3CreateMode types
* Support determining the size of Nfs3CallResult objects. In some cases, the NFS protocol describes the maximum length of some messages. You can use `GetSize` to determine the current size and decide whether the message can be sent or not.
* Override ToString on some elements for easier debugging
> Add missing Nfs3CommitResult, Nfs3CreateMode types

- Library/DiscUtils.Nfs/MountProc3.cs
- Library/DiscUtils.Nfs/Nfs3.cs
- Library/DiscUtils.Nfs/Nfs3FileHandle.cs
- Library/DiscUtils.Nfs/Nfs3Mount.cs
- Library/DiscUtils.Nfs/Nfs3SetAttributes.cs
- Library/DiscUtils.Nfs/NfsProc3.cs
- Library/DiscUtils.Nfs/PortMapProc2.cs
- Library/DiscUtils.Nfs/RpcAcceptStatus.cs
- Library/DiscUtils.Nfs/RpcAcceptedReplyHeader.cs
- Library/DiscUtils.Nfs/RpcAuthenticationStatus.cs
- Library/DiscUtils.Nfs/RpcIdentifiers.cs
- Library/DiscUtils.Nfs/RpcMessageHeader.cs
- Library/DiscUtils.Nfs/RpcMismatchInfo.cs
- Library/DiscUtils.Nfs/RpcRejectedReplyHeader.cs
- Library/DiscUtils.Nfs/RpcRejectedStatus.cs
- Library/DiscUtils.Nfs/RpcReplyHeader.cs
- Library/DiscUtils.Nfs/RpcReplyStatus.cs
* Mark RPC-related classes as public so we can implement an RPC server in `DiscUtils.Nfs.Server`.
* Add missing file headers
* Centralize all RPC identifiers in RpcIdentifiers
> Mark RPC-related classes as public 

- Library/DiscUtils.Ext/BlockGroup.cs
- Library/DiscUtils.Ext/SuperBlock.cs
- Library/DiscUtils.Ext/VfsExtFileSystem.cs
To fix this issue: https://github.com/DiscUtils/DiscUtils/issues/130
> Ext4 Fix BlockGroup64 descriptor size to use superblock value

- Library/DiscUtils.Ntfs/BiosParameterBlock.cs
Related to issue #146 __BiosParameterBlock.IsValid fails for NTFS in Microsoft Xbox One virtual filesystem__:
- Validate BiosParameterBlock by checking OemId
> Ntfs/BiosParameterBlock: Check OemId instead of SignatureByte

- LICENSE.txt
- Library/DiscUtils.BootConfig/DiscUtils.BootConfig.csproj
- Library/common.props
- Use the `PackageLicenseExpression` property so that NuGet can recognize the MIT license used
- Simplify the LICENSE.txt file, so that GitHub hopefully recognizes this as a MIT license
> Update package license information

- Library/common.props
- appveyor.yml
Allows publishing of the source code of DiscUtils using a `.snupkg` package, and patching of the symbol files so that they reference the source code on GitHub.
> Enable SourceLink support

- Library/DiscUtils.Core/CoreCompat/EncodingHelper.cs
- Library/DiscUtils.Core/CoreCompat/StringExtensions.cs
- Library/DiscUtils.Core/DiscFileSystem.cs
- Library/DiscUtils.Core/Internal/LocalFileLocator.cs
- Library/DiscUtils.Core/InvalidFileSystemException.cs
- Library/DiscUtils.Core/Plist.cs
- Library/DiscUtils.Core/System/DateTimeOffsetExtensions.cs
- Library/DiscUtils.Core/VirtualDisk.cs
- Library/DiscUtils.Core/VolumeInfo.cs
- Library/DiscUtils.Core/VolumeManager.cs
- Library/DiscUtils.Iscsi/Connection.cs
- Library/DiscUtils.Iscsi/InvalidProtocolException.cs
- Library/DiscUtils.Iscsi/IscsiException.cs
- Library/DiscUtils.Iscsi/LoginException.cs
- Library/DiscUtils.Iscsi/ScsiCommandException.cs
- Library/DiscUtils.Nfs/Nfs3Exception.cs
- Library/DiscUtils.Nfs/RpcException.cs
- Library/DiscUtils.Nfs/RpcTcpTransport.cs
- Library/DiscUtils.Ntfs/NtfsFileSystemChecker.cs
- Library/DiscUtils.Registry/RegistryCorruptException.cs
- Library/DiscUtils.Streams/Buffer/Buffer.cs
- Library/DiscUtils.Vhd/FileChecker.cs
- Library/DiscUtils.Vhdx/Metadata.cs
- Library/DiscUtils.Xva/HashStreamCore.cs
- Library/DiscUtils.Xva/VirtualMachineBuilder.cs
- Library/DiscUtils/SetupHelper.cs
- Library/common.props
- Use standardized preprocessor variables (`NETSTANDARD`, `NETSTANDARD1_5`, `NETSTANDARD2_0`, `NET20`, `NET45`,...) instead of custom ones
- Don't use CAS or MarshalByRef on .NET Core at all
- Don't use serialization on .NET Core 1.x, but do enable it on .NET Core 2.x
> Cleanup conditional compilation

- Library/DiscUtils.Lvm/LogicalVolumeManager.cs
- Library/DiscUtils.Lvm/PhysicalVolume.cs
Currently the `VolumeManager` also reports lvm physical volumes as logical volumes if the partition has a wrong partition type.
```csharp
var logical = new VolumeManager(disk).GetLogicalVolumes();
//now logical contains each PV with a wrong partition type in addition to the logical volumes residing on those PV
```
This change unifies the behavior of LVM `LogicalVolumeManagerFactory.HandlesPhysicalVolume` and `LogicalVolumeManagerFactory.MapDisk`.
I've seen many LVM installation with the default partition type `Linux Filesystem` since the linux kernel doesn't care.
> lvm pv detection

- Tests/LibraryTests/Btrfs/SampleDataTests.cs
- Tests/LibraryTests/Buffers/BufferTest.cs
- Tests/LibraryTests/DiscFileSystemDirectoryTest.cs
- Tests/LibraryTests/DiscFileSystemFileTest.cs
- Tests/LibraryTests/Fat/FatFileSystemTest.cs
- Tests/LibraryTests/FileSystemManagerTest.cs
- Tests/LibraryTests/Iso9660/IsoDirectoryInfoTest.cs
- Tests/LibraryTests/Iso9660/SampleDataTests.cs
- Tests/LibraryTests/Ntfs/NtfsFileSystemTest.cs
- Tests/LibraryTests/SquashFs/SquashFileSystemBuilderTest.cs
- Tests/LibraryTests/StreamExtentTest.cs
- Tests/LibraryTests/Swap/SampleDataTests.cs
- Tests/LibraryTests/ThreadSafeStreamTest.cs
- Tests/LibraryTests/Vhd/DiskBuilderTest.cs
- Tests/LibraryTests/Vhd/DynamicStreamTest.cs
- Tests/LibraryTests/Vhdx/DiskBuilderTest.cs
- Tests/LibraryTests/Vmdk/DiskTest.cs
- Tests/LibraryTests/Vmdk/DynamicStreamTest.cs
- Tests/LibraryTests/Xfs/SampleDataTests.cs
- Tests/LibraryTests/Xva/VirtualMachineBuilderTest.cs
- Use `Assert.Single`, `Assert.True` and `Assert.False` instead of `Assert.Equal` constructs
- Mark theories with the `[Theory]` attribute
- Make non-test methods private
> Fix xunit warnings

- Library/DiscUtils.Net/DiscUtils.Net.csproj
- Library/DiscUtils.OpticalDiscSharing/DiscUtils.OpticalDiscSharing.csproj
- Library/common-library.props
- Tests/LibraryTests/LibraryTests.csproj
- Utilities/DiscUtils.Common/DiscUtils.Common.csproj
- Utilities/DiscUtils.Diagnostics/DiscUtils.Diagnostics.csproj
This enables checking cloning DiscUtils on say, macOS or Linux building with `dotnet build` without having to change of the project files.
- Only target `net20` when using full MSBuild (`MSBuildRuntimeType == Full`)
- Only target `net40` & `net45` when building on Windows (`OS == Windows_NT`)
> Support building with dotnet build, Linux

- Library/DiscUtils.BootConfig/Properties/AssemblyInfo.cs
- Library/DiscUtils.Containers/Properties/AssemblyInfo.cs
- Library/DiscUtils.Core/Properties/AssemblyInfo.cs
- Library/DiscUtils.Dmg/Properties/AssemblyInfo.cs
- Library/DiscUtils.Ext/Properties/AssemblyInfo.cs
- Library/DiscUtils.Fat/Properties/AssemblyInfo.cs
- Library/DiscUtils.FileSystems/Properties/AssemblyInfo.cs
- Library/DiscUtils.HfsPlus/Properties/AssemblyInfo.cs
- Library/DiscUtils.Iscsi/Properties/AssemblyInfo.cs
- Library/DiscUtils.Iso9660/Properties/AssemblyInfo.cs
- Library/DiscUtils.Net/Properties/AssemblyInfo.cs
- Library/DiscUtils.Nfs/Properties/AssemblyInfo.cs
- Library/DiscUtils.Ntfs/Properties/AssemblyInfo.cs
- Library/DiscUtils.OpticalDiscSharing/Properties/AssemblyInfo.cs
- Library/DiscUtils.OpticalDisk/Properties/AssemblyInfo.cs
- Library/DiscUtils.Registry/Properties/AssemblyInfo.cs
- Library/DiscUtils.Sdi/Properties/AssemblyInfo.cs
- Library/DiscUtils.SquashFs/Properties/AssemblyInfo.cs
- Library/DiscUtils.Streams/Properties/AssemblyInfo.cs
- Library/DiscUtils.Transports/Properties/AssemblyInfo.cs
- Library/DiscUtils.Udf/Properties/AssemblyInfo.cs
- Library/DiscUtils.Vdi/Properties/AssemblyInfo.cs
- Library/DiscUtils.Vhd/Properties/AssemblyInfo.cs
- Library/DiscUtils.Vhdx/Properties/AssemblyInfo.cs
- Library/DiscUtils.Vmdk/Properties/AssemblyInfo.cs
- Library/DiscUtils.Wim/Properties/AssemblyInfo.cs
- Library/DiscUtils.Xva/Properties/AssemblyInfo.cs
- Library/DiscUtils/Properties/AssemblyInfo.cs
- Library/common-library.props
The .NET Core SDK can autogenerate these attributes, which makes for less code to maintain.
> Use auto-generated assembly attributes

- Library/DiscUtils.HfsPlus/CompressionAttribute.cs
- Library/DiscUtils.HfsPlus/File.cs
- Library/DiscUtils.HfsPlus/FileCompressionType.cs
- Tests/LibraryTests/HfsPlus/HfsPlusTest.cs
- Tests/LibraryTests/MacOSOnlyTheoryAttribute.cs
This PR adds support for files in the HFS+ file system which are compressed using compression type 9 ("`DECMPFS_TYPE_RAW_ATTR `"). This compression type means the file is stored uncompressed in the `com.apple.decmpfs` attribute.
The best write-up of the compression types I could find is here: https://github.com/RJVB/afsctool/issues/6#issuecomment-374620414 .
Only a couple of these compression types are supported by DiscUtils. I've updated the code to error out (instead of silently returning an invalid stream).
> HFS+: Add support for compression type 9 ("DECMPFS_TYPE_RAW_ATTR")

- appveyor.yml
CI in the develop branch is failing because the `symbol_server` property is not set for the MyGet feed, causing symbols to be pushed to NuGet instead (which fails, because the API key is incorrect).
This should fix CI on the develop branch.
> Push symbols to MyGet

- Library/DiscUtils.Core/ApplePartitionMap/PartitionMapEntry.cs
- Library/DiscUtils.Core/FileLocator.cs
- Library/DiscUtils.Core/Internal/VirtualDiskFactory.cs
- Library/DiscUtils.Core/Internal/VirtualDiskFactoryAttribute.cs
- Library/DiscUtils.Core/Partitions/BiosPartitionInfo.cs
- Library/DiscUtils.Core/Partitions/GuidPartitionInfo.cs
- Library/DiscUtils.Core/Partitions/PartitionInfo.cs
- Library/DiscUtils.Core/Raw/DiskImageFile.cs
- Library/DiscUtils.Core/VirtualDiskLayer.cs
- Library/DiscUtils.Dmg/DiskImageFile.cs
- Library/DiscUtils.Dmg/UdifPartitionInfo.cs
- Library/DiscUtils.OpticalDiscSharing/DiscImageFile.cs
- Library/DiscUtils.OpticalDisk/DiscImageFile.cs
- Library/DiscUtils.Vdi/DiskImageFile.cs
- Library/DiscUtils.Vhd/DiskImageFile.cs
- Library/DiscUtils.Vhdx/DiskImageFile.cs
- Library/DiscUtils.Vmdk/DiskImageFile.cs
- Library/DiscUtils.Xva/DiskLayer.cs
Currently, it's difficult to build and maintain out-of-tree extensions to DiscUtils. Some classes which you need to implement are either `internal`, or have (abstract) methods or properties which are `internal`. This makes it impossible to implement these classes in a 3rd party project.
This commit improves DiscUtils extensibility a bit by:
- Making `VirtualDiskFactory`, `VirtualDiskFactoryAttribute` public
- Making `FileLocator` public
- Making `PartitionInfo.VolumeType` public
- Making `VirtualDiskLayer.Capacity` and `VirtualDiskLayer.RelativeFileLocator` public
> Improve DiscUtils extensibility

- Library/DiscUtils.Containers/DiscUtils.Containers.csproj
- Library/DiscUtils.Core/CoreCompat/ReflectionHelper.cs
- Library/DiscUtils.Core/DiscUtils.Core.csproj
- Library/DiscUtils.Core/Internal/LocalFileLocator.cs
- Library/DiscUtils.Core/InvalidFileSystemException.cs
- Library/DiscUtils.Core/System/DateTimeOffsetExtensions.cs
- Library/DiscUtils.Iscsi/DiscUtils.Iscsi.csproj
- Library/DiscUtils.Iscsi/InvalidProtocolException.cs
- Library/DiscUtils.Iscsi/IscsiException.cs
- Library/DiscUtils.Iscsi/LoginException.cs
- Library/DiscUtils.Iscsi/ScsiCommandException.cs
- Library/DiscUtils.Nfs/DiscUtils.Nfs.csproj
- Library/DiscUtils.Nfs/Nfs3Exception.cs
- Library/DiscUtils.Nfs/RpcException.cs
- Library/DiscUtils.Ntfs/Properties/AssemblyInfo.cs
- Library/DiscUtils.Registry/DiscUtils.Registry.csproj
- Library/DiscUtils.Registry/RegistryCorruptException.cs
- Library/DiscUtils.Vhd/FileChecker.cs
- Library/DiscUtils/DiscUtils.csproj
- Library/DiscUtils/SetupHelper.cs
- Library/common-library.props
This PR
- Adds the `net5.0` target
- Removes dependencies on packages which ship inbox in `netstandard2.0` and `net5.0` (such as `System.IO.FileSystem.DriveInfo` , `System.Threading.Thread`, `System.Net.Sockets` and `System.Xml.XmlDocument`.
- Annotates DicsUtils.Ntfs as Windows-only on net5.0, because it has a dependency on `SecurityIdentifier` (via `Quotas.cs`) which is marked as Windows-only.
> Add .NET 5.0 support, remove netstandard1.5 workarounds

- Library/DiscUtils.Registry/Properties/AssemblyInfo.cs
- Library/DiscUtils.Vhdx/Metadata.cs
- appveyor.yml
This removes a dependency on chocolatey during the build process.
> Use `dotnet tool` to install GitVersion

- Library/DiscUtils.Vmdk/DescriptorFile.cs
- Library/DiscUtils.Vmdk/DiskCreateType.cs
- Library/DiscUtils.Vmdk/DiskImageFile.cs
- Library/DiscUtils.Vmdk/ExtentDescriptor.cs
- Library/DiscUtils.Vmdk/ExtentType.cs
This pull request add the initial support to the VMDK SeSparse and VsanSparse disk types.
The initial support only allows to open the disk (`VirtualDisk.OpenDisk`) and read the various values there (like `Capacity`, `Geometry`,...)
Every further operation which involves reading the actual data from the underlying stream will fail with the  exception message (ex: `Extent type 'SESPARSE' not supported`)
Creating disk (`Disk.Initialize`) for these 2 new types will fail with the exception message `Creating disks of this type is not supported`
> VMDK: Add initial support to SeSparse and VsanSparse disks
